<?php

/**
 * Install default config.
 */
function entity_pdf_update_8001() {
  \Drupal::configFactory()->getEditable('entity_pdf.settings')
    ->set('filename', '[node:nid].pdf')
    ->save();
}

/**
 * Add default config for tempDir
 */
function entity_pdf_update_8002() {
  \Drupal::configFactory()->getEditable('entity_pdf.settings')
    ->set('tempDir', 'sites/default/files/entity_pdf')
    ->save();
}
